python main.py \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation_final.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 50 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--seed 9223 \
--num_workers 0 \
--weight_decay 5e-5 \
--lr_ed 5e-5
